version: '3.7'

services:

  # ~~~~ ZooKeeper ~~~~
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    container_name: zookeeper
    hostname: zookeeper
    ports:
        - "2181:2181"
    environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_SERVER_ID: "1"
        # Save Memory of your PC - Limits Max and Mix Heap Size
        ZOOKEEPER_HEAP_OPTS: -Xms1g -Xms1g
    networks: 
        - cryptolover

  # ~~~~ Kafka ~~~~
  kafkaserver:
    image: confluentinc/cp-kafka:6.1.1
    container_name: kafkaserver
    hostname: kafkaserver
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafkaserver:9092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_METADATA_TOPIC_REPLICATION_FACTOR: 1
      # Save Memory of your PC - Limits Max and Mix Heap Size
      KAFKA_HEAP_OPTS: -Xms1g -Xms1g
    networks: 
        - cryptolover 

  # ~~~~ Kafka Topic Creation $MONEY$ ~~~~
  kafka-create-topics:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
        - kafkaserver
    container_name: kafka-create-topics
    hostname: kafka-create-topics
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
                        cub kafka-ready -b kafkaserver:9092 1 200 && \
                        kafka-topics --create --topic cryptocurrencies-raw --if-not-exists --zookeeper zookeeper:2181 --partitions 1 --replication-factor 1 && \
                        kafka-topics --create --topic cryptocurrencies --if-not-exists --zookeeper zookeeper:2181 --partitions 1 --replication-factor 1 && \
                        sleep infinity'"
    environment:
        KAFKA_BROKER_ID: ignored
        KAFKA_ZOOKEEPER_CONNECT: ignored
        # Save Memory of your PC - Limits Max and Mix Heap Size
        KAFKA_HEAP_OPTS: -Xms1g -Xms1g
    networks:
        - cryptolover

  # ~~~~ KafkaStream (Life is sadness) ~~~~
  kafkastream:
    build: 
        context: kafkastream
    image: cryptosight:kafkastream
    container_name: kafkastream
    depends_on: 
        - kafka-create-topics
    networks:
        - cryptolover

  # ~~~~ KafkaUI ~~~~
  kafkaWebUI:
    image: provectuslabs/kafka-ui:latest
    container_name: kafkaWebUI
    environment:
        KAFKA_CLUSTERS_0_NAME: CryptoSnapshots
        KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafkaserver:9092
        # Save Memory of your PC - Limits Max and Mix Heap Size
        KAFKA_CLUSTERS_0_HEAP_OPTS: -Xms1g -Xms1g
    ports: 
        - 8080:8080
    depends_on:
        - kafkaserver
    networks: 
        - cryptolover

  # ~~~~ Logstash HTTP Poller ~~~~
  logstash_http_poller:
    container_name: logstash_http_poller
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin
    volumes: 
        - $PWD/logstash/http_poller/:/usr/share/logstash/pipeline/
    depends_on: 
        - kafka-create-topics
    environment:
        # Save Memory of your PC - Limits Max and Mix Heap Size
        - "LS_JAVA_OPTS=-Xms1g -Xmx1g"
    networks: 
      - cryptolover

  # ~~~~ OpenSearch (ElasticSearch just made FOSS) ~~~~
  opensearch:
    container_name: opensearch
    hostname: opensearch
    image: opensearchproject/opensearch:latest
    environment:
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      # Memory Settings
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - cryptolover

  # ~~~~ OpenSearch-Dashboards (Kibana just made FOSS) ~~~~
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    depends_on: 
      - opensearch
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    networks:
      - cryptolover

  # ~~~~ Logstash OpenSearch Consumer ~~~~
  logstash_opensearch:
    container_name: logstash_opensearch
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin
    volumes: 
        - $PWD/logstash/opensearch_consumer/:/usr/share/logstash/pipeline/
    depends_on: 
        - kafkastream
        - opensearch
        - logstash_http_poller
    environment:
        # Save Memory of your PC - Limits Max and Mix Heap Size
        - "LS_JAVA_OPTS=-Xms1g -Xmx1g"
    networks: 
      - cryptolover

  # ~~~~ Spark and ML ~~~~  
  spark:
    build: 
      context: spark
    image: cryptosight:spark
    container_name: spark
    depends_on: 
      - kafkastream
      - opensearch
    networks: 
        - cryptolover

volumes:
  opensearch-data:

networks:
  cryptolover:
    name: cryptolover
    driver: bridge